theme: jekyll-theme-slate
nav:
- name: Home
  link: /
- name: About
  link: /about.html


<nav>
  {% for item in site.nav %}
    <a href="{{ item.link }}" 
      {% if page.url == item.link %} style="color: red;" {% endif %}
    >
      {{ item.name }}
    </a>
  {% endfor %}
</nav>
